name: Node.js Package

on:
  push:
    branches: ["prod"]
  pull_request:
    branches: ["prod"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses : actions/checkout@v2

      - name: Setup Node.js
        uses : actions/setup-node@v1
        with :
          node-version : 18
          registry-url : https://npm.pkg.github.com
          scope : '@lithium-framework'
      
      - name: Add authentication token to ~/.npmrc
        run: echo "@lithium-framework:registry=https://npm.pkg.github.com/" > .npmrc && echo "//npm.pkg.github.com/:_authToken=${{secrets.PUBLISH_TOKEN}}" >> .npmrc

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript files
        run: npx --yes tsc

      - name: Publish to GitHub Packages
        run: npm publish

